### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by psmoros** [xmlpull-org/xmlpull-api-v1#2]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ellord0xd) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by aslom** [comment]
Added SECURITY - how can I contact you?

**Comment by psmoros** [comment]
What's the best email to reach you? Mine is pavlos@418sec.com  :)

**Comment by psmoros** [comment]
For the record the reports don't look too serious but we'll transmit them nonetheless

**Comment by aslom** [comment]
I have sent you email
